DROP TABLE IF EXISTS instance_params;

DROP TABLE IF EXISTS instances;

DROP TABLE IF EXISTS sessions;

DROP TABLE IF EXISTS task_params;

DROP TABLE IF EXISTS tasks;

DROP TABLE IF EXISTS log_entries;

DROP TABLE IF EXISTS files;